### ISSUE TITLE
报错 Error: Uh oh!

### ISSUE THREAD

**Issue by jl6278462** [weex-plugins/weex-amap#12]
`D:\workspace\appName>weexpack plugin add D:\workspace\weex-plugins\weex-plugin-amap
Installing "weex-plugin-amap" for android
Dependent plugin "weex-adapter-image" already installed on android.
Android Studio project detected
ANDROID_HOME=C:\Users\qian\AppData\Local\Android\sdk
JAVA_HOME=C:\Program Files\java\jdk1.8.0_121
WEEXPACK datacordova.gradle.include.1=com.amap.api:map3d-native:latest.integration
cordova.gradle.include.2=com.amap.api:map3d:latest.integration
cordova.gradle.include.3=com.amap.api:location:latest.integration
Incremental java compilation is an incubating feature.                                                                       
:clean UP-TO-DATE                                                                                                                    
:app:clean
:appframework:clean
:weexplugin:clean

BUILD SUCCESSFUL

Total time: 1.938 secs
`
`Error during processing of action! Attempting to revert...
Failed to install 'weex-plugin-amap':weexpack error: Uh oh!
"D:\workspace\appName\platforms\android\weexplugin\src\main\java\com\alibaba\weex\amap\component\WXMapViewComponent.java" already exists!
    at copyNewFile (C:\Users\qian\AppData\Roaming\npm\node_modules\weexpack\node_modules\.0.1.3@weexpack-lib\src\platforms\android_pack\lib\pl
    at install (C:\Users\qian\AppData\Roaming\npm\node_modules\weexpack\node_modules\.0.1.3@weexpack-lib\src\platforms\android_pack\lib\plugin
    at Object.process (C:\Users\qian\AppData\Roaming\npm\node_modules\weexpack\node_modules\.0.1.1@weexpack-common\src\ActionStack.js:56:25)
    at PluginManager.doOperation (C:\Users\qian\AppData\Roaming\npm\node_modules\weexpack\node_modules\.0.1.1@weexpack-common\src\PluginManage
    at PluginManager.addPlugin (C:\Users\qian\AppData\Roaming\npm\node_modules\weexpack\node_modules\.0.1.1@weexpack-common\src\PluginManager.
    at C:\Users\qian\AppData\Roaming\npm\node_modules\weexpack\node_modules\.0.1.3@weexpack-lib\src\platforms\android_pack\Api.js:253:18
    at _fulfilled (C:\Users\qian\AppData\Roaming\npm\node_modules\weexpack\node_modules\.1.0.1@q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\qian\AppData\Roaming\npm\node_modules\weexpack\node_modules\.1.0.1@q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\qian\AppData\Roaming\npm\node_modules\weexpack\node_modules\.1.0.1@q\q.js:749:13)
    at C:\Users\qian\AppData\Roaming\npm\node_modules\weexpack\node_modules\.1.0.1@q\q.js:557:44
Error: Uh oh!
"D:\workspace\appName\platforms\android\weexplugin\src\main\java\com\alibaba\weex\amap\component\WXMapViewComponent.java" already exists!
`
本地添加插件，报如下错误，希望作者帮忙看下，什么情况。。。。。。

**Comment by littleseven** [comment]
Failed to install 'weex-plugin-amap':weexpack error: Uh oh!
"D:\workspace\appName\platforms\android\weexplugin\src\main\java\com\alibaba\weex\amap\component\WXMapViewComponent.java" already exists!

报错说文件已经存在了，说明做了重复添加。可以weexpack platform remove android后，重新添加platfrom和插件
